name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  ci_test:
    name: Check if Build should be done
    runs-on: self-hosted
    steps:
      - name: sleep
        run: sleep 10s
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: invaild/cachekey
          path: |
            1.txt
      # - name: Built Code Cache
      #   uses: actions/cache@v3.3.1
      #   with:
      #     key: cache-key,-3
      #     path: ~/cachecontent
      - name: sleep
        run: sleep 10s
