name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  ci_test:
    name: Check if Build should be done
    runs-on: ubuntu-latest
    steps:
      - name: test
        env:
          SLACK_BOT_TOKEN: 12344
        uses: abinoda/slack-action@master
      - name: sleep
        run: sleep 5m
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: invaild/cachekey
          path: |
            ~/cachecontent
      # - name: Built Code Cache
      #   uses: actions/cache@v3.3.1
      #   with:
      #     key: cache-key,-3
      #     path: ~/cachecontent
      - name: sleep
        run: sleep 10s
